apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital
      app.kubernetes.io/name: cv3-ambulance-wl
      wac-fiit.github.io/project: cv3-ambulance-wl
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../../apps/cv3-ambulance-ufe
  - ../../../apps/cv3-ambulance-webapi

components:
  - ../../../components/version-release
